In [ ]:
import pandas as pd
import os
import pydantic

In [ ]:
"""|Operador | Operacion |
|suma| + |
|resta| - |
|Multiplicacion| * |
|Division| / |
|Division entera| // |
| Modulo| % |
|Potencial ** o Libreria math (pow) |
|raiz|"""

In [ ]:
#0.8,0.5 para gato mayor igual que 0.5
#0.3 para perro menor que 0.3
#forward propagation
#back propagation = disminuir el error

entradas = [0.8,0.3,0.5]
pesos = [0.4,0.7,0.2]
sesgo = 0.1
#yp = (x1 * w1) + (x2 * w2) + (x3 * w3)

yp = (entradas[0] * pesos[0]) + (entradas[1] * pesos[1]) + (entradas[2] * pesos[2]) + sesgo
print(f'yp: {yp}')
if yp >= 0.5:
    print("gato")
else:
    print('perro')

yp: 0.73
gato


In [1]:
# Realizar una neurona artificial de 4 entradas y la clasificacion 3 "gato", "perro", "ave" donde la probabilidad de gato
# sea ‹0.15 , La probabilidad de perro sea › 0.68, la probabilidad de 0.15 a 0.68 sea de "ave" x1, x2, x3 y x4 valdran
# 0.5,0. 67,0.85, 0.32 respectivamente y los pesos w1,w2, w3,w4 seran 0.14,0.22,0.07,0.10 respectivamente y el bias(sesgo) valdra 0.




entradas = [0.5,0.67,0.85,0.32]
pesos = [0.14,0.22,0.07,0.10]
sesgo = 0.09
yp = 0

for i in range(len(entradas)):
    yp = yp + (entradas[i] * pesos[i])

yp = yp + sesgo

if yp < 0.15:
    print('GATO')
elif yp > 0.68:
    print('PERRO')
else:
    print('AVE')

AVE


In [ ]:
def nerurona(entradas, pesos, sesgo, yp):

    for i in range(len(entradas)):
        yp = yp + (entradas[i] * pesos[i])

    yp = yp + sesgo

    return yp

entradas = [0.5,0.67,0.85,0.32]
pesos = [0.14,0.22,0.07,0.10]
sesgo = 0.09
yp = 0

nerurona(entradas, pesos, sesgo,yp)

In [1]:

import math

x = [1.5,0.8,-0.4]
w = [0.6,-0.3,0.9]
b = 0.1

z = sum(x1 * w1 for x1, w1 in zip(x,w)) + b
print(f'Suma ponderada z = {z:.4f}')

def sigmoide(z):
    return 1 / (1 + math.exp(-z))

activavion = sigmoide(z)
print(f"Activacion o(z) = {activavion:.4f}")

clase = 1 if activavion >= 0.5 else 0
print(f'Clase predicha: {clase}')

Suma ponderada z = 0.4000
Activacion o(z) = 0.5987
Clase predicha: 1


In [15]:
import numpy as np

arreglo1D = np.array([5,8,7,5])
print(type(arreglo1D))
      
arreglo2D = np.array([[1,2,3,4],[5,6,7,8]])
print(type(arreglo2D))

arreglo3D = np.array([[[1,2,3],[4,5,6,]],[[7,8,9],[10,11,12]]])
print(type(arreglo3D))

print(arreglo3D)

print(arreglo3D.ndim)

print(arreglo3D.size)

print(arreglo3D.shape)

print('max')
print(np.max(arreglo1D))
print(np.max(arreglo2D))
print(np.max(arreglo3D))
print('min')
print(np.min(arreglo1D))
print(np.min(arreglo2D))
print(np.min(arreglo3D))
print('mean')
print(np.mean(arreglo1D))
print(np.mean(arreglo2D))
print(np.mean(arreglo3D))
print('sum')
print(np.sum(arreglo1D))
print(np.sum(arreglo2D))
print(np.sum(arreglo3D))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
12
(2, 2, 3)
max
8
8
12
min
5
1
1
mean
6.25
4.5
6.5
sum
25
36
78


In [19]:
entradas = np.array([0.5,0.67,0.85,0.32])
pesos = np.array([0.14,0.22,0.07,0.10])
sesgo = 0.09
yp = np.dot(entradas,pesos) + sesgo

print(yp)

fyp = 1 / np.exp(-yp)
print(fyp)

if fyp < 0.15:
    print('GATO')
elif fyp > 0.68:
    print('PERRO')
else:
    print('AVE')

0.39890000000000003
1.4901845926969617
PERRO


In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
url = 'https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv'
df = pd.read_csv(url)
df.head(10)

plt.figure()
plt.labelx()
plt.labely()
plt.title()
plt.show()
plt.scatter()


<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

In [ ]:

TAREA:

investigar las funciones sklearn